stages:
  - run

run:
  tags:
    - main
  only:
    - main
  stage: run
  script:
    - sh ./shellscripts/run.sh

#run_pred:
#  tags:
#    - test
#  only:
#    - predictor
#  stage: run
#  script:
#    - sh ./shellscripts/run_pred.sh

